name: SustentApp - Pull Request

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Generate Test Report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.6
        with:
            reports: coverage/**/coverage.cobertura.xml
            targetdir: coveragereport
            assemblyfilters: '+SustentApp.Domain*'
            classfilters: '+*;-*Exception;-*Command;-*Filter;'
            reporttypes: 'MarkdownSummaryGithub'

      - name: Add comment to PR
        if: github.event_name == 'pull_request'
        run: gh pr comment $PR_NUMBER --body-file coveragereport/SummaryGithub.md
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PR_NUMBER: ${{ github.event.number }}
